# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='BASE_DIR/media'),
        ),
    ]
