# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170105_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='smedia'),
        ),
    ]
