# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score_return',
            old_name='Image',
            new_name='Score',
        ),
    ]
