# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0002_auto_20161229_1049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score_Return',
        ),
        migrations.AddField(
            model_name='details',
            name='Score',
            field=models.FloatField(default=0.0),
        ),
    ]
