# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0003_auto_20161229_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score_Return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='details',
            name='Score',
        ),
    ]
